base/urls.py
from django.urls import path
from . import views
from .views import *

app_name = 'base'

urlpatterns = [
    path('', views.main, name="main"),
    path('info/', views.info, name="info"),
    path('geo/', views.geo, name="geo"),
    path('VR/', views.VR, name="VR"),
    path('math/', views.math, name="math"),
    path('informatics/', views.informatics, name="informatics"),
    path('physics/', views.physics, name="physics"),
    path('chemistry/', views.chemistry, name="chemistry"),
    path('projects/', Projects.as_view(), name="projects"),
    path('add_project/', Add_project.as_view(), name="add_project"),
    path('account/login/', views.login_user, name='login'),
    path('account/profile/', views.profile, name='profile'),
    path('account/register/', RegisterView.as_view(), name='register'),
    path('logout/', Logout.as_view(), name='logout'),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
]

base/models.py
from django.db import models
from django.contrib.auth.models import User


class Project(models.Model):
    author = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    title = models.CharField(max_length = 100)
    text = models.TextField()

class Profile(models.Model):
    user = models.ForeignKey('auth.User', on_delete=models.CASCADE)
    username = models.CharField(max_length = 100)
    scores = models.IntegerField()
    

base/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.views.generic.edit import FormView

class ProjectsForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['title', 'text',]

class Loginform(forms.Form):
    username= forms.CharField(max_length= 50,label="Enter username")
    password= forms.CharField(max_length= 30, label='Password', widget=forms.PasswordInput)

class RegisterUserForm(UserCreationForm):
    
    username = forms.CharField(label='Логин', 
                               widget=forms.TextInput(attrs={'class': 'form-input',
                                                             'style': 'width:180px;height:18px'
                                                             }))
    email = forms.EmailField(label='Email', 
                               widget=forms.EmailInput(attrs={'class': 'form-input',
                                                              'style': 'width:180px;height:18px'
                                                              }))
    password1 = forms.CharField(label='Пароль', 
                               widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                 'style': 'width:180px;height:18px'
                                                                 }))
    password2 = forms.CharField(label='Повтор пароля', 
                               widget=forms.PasswordInput(attrs={'class': 'form-input',
                                                                 'style': 'width:180px;height:18px'
                                                                 }))
    class Meta:
        model = User
        fields = {'email', 'username', 'password2','password1'}
    def form_valid(self, form):
        # Создаём пользователя, если данные в форму были введены корректно.
        form.save()

        # Вызываем метод базового класса
        return super(RegisterFormView, self).form_valid(form)

base/views.py
from django.core.exceptions import MultipleObjectsReturned, ObjectDoesNotExist
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from .forms import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic.base import *
from django.views.generic import *

def main(request):
    data = {}
    return render(request, 'base.html', data)

class Projects(TemplateView):
    template_name = 'projects.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context
    def dispatch(self, request, *args, **kwargs):
        data = {
            'projects': Project.objects.all()[::-1],
                }
        return render(request, self.template_name, data)


class Add_project(TemplateView):
    template_name = 'add_project.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            data = {
                'form': ProjectsForm,
                }
            if request.method == 'POST':
                form = ProjectsForm(request.POST, request.FILES)
                if form.is_valid():
                    title = form.cleaned_data.get("title")
                    text = form.cleaned_data.get("text")
                    Project.objects.create(text=text, title=title, author_id=request.user.id)
                    a = Profile.objects.get(user_id=request.user.id)
                    a.scores+=10
                    a.save()
                    return redirect('base:projects')
                else:
                    form = ProjectsForm
                    messages.error(request, f'что-то не так')
            else:
                form = ProjectsForm
            data['form'] = form
            return render(request, self.template_name, data)
        else:
            return redirect('exel:login')

def geo(request):
    data = {
        
        }
    return render(request, 'geo.html', data)

def VR(request):
    data = {
        
        }
    return render(request, 'VR.html', data)    

def chemistry(request):
    data = {
        
        }
    return render(request, 'chemistry.html', data)    

def physics(request):
    data = {
        
        }
    return render(request, 'physics.html', data)    

def math(request):
    data = {
        
        }
    return render(request, 'math.html', data)    

def informatics(request):
    data = {
        
        }
    return render(request, 'informatics.html', data) 

def info(request):
    data = {
        
        }
    return render(request, 'info.html', data) 

def profile(request):
    if request.user.is_authenticated:
        data = {
            'profile': Profile.objects.get(user_id=request.user.id),
            'users': Profile.objects.order_by("-scores"),
            }
        return render(request, 'registration/profile.html', data)
    else:
        return redirect('base:login')    

class RegisterView(CreateView):
    form_class  = RegisterUserForm
    template_name = 'registration/register.html'
    
    def get_success_url(self):
        return reverse('base:login')
    
    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        return dict(list(context.items()))
    
class Logout(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        return redirect('base:login')
    
def login_user(request):
    uservalue=''
    passwordvalue=''

    form = Loginform(request.POST or None)
    if form.is_valid():
        uservalue = form.cleaned_data.get("username")
        passwordvalue = form.cleaned_data.get("password")

        user = authenticate(username=uservalue, password=passwordvalue)
        if user is not None:
            login(request, user)
            try:
                Profile.objects.get(user_id=user.id)
            except ObjectDoesNotExist:
                Profile.objects.create(scores=0, user_id=user.id, username=uservalue)
            return redirect('base:main')
        else:
            context = {'form': form}
            return render(request, 'registration/login.html', context) 
    else:
        context = {'form': form}
        return render(request, 'registration/login.html', context)    

base/templates/VR.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/add_project.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>
    <form method="post">
    {% csrf_token %}
        {{form.title}}<br>
        {{form.text}}<br>
        <input type="submit" value="Добавить">
    </form>

{% endblock %}

base/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
    <head>
        <meta charset="UTF-8">
        
        <title>{% block title %}Главная страница{% endblock %}</title>
        
        <link rel="stylesheet" href="{% static 'base.css' %}" type="text/css">
        <meta name="description" content="Panorama — A-Frame">
        <script src="https://aframe.io/releases/1.2.0/aframe.min.js"></script>
    </head>
    
    <body>
        {% block content %}
            
            <a href="{% url 'base:projects' %}" class="button">Проекты</a>
            <a href="{% url 'base:profile' %}" class="button">Профиль</a>
            <a href="{% url 'base:info' %}" class="button">Инфо</a>
            <br>
            
            <a href="{% url 'base:chemistry' %}" class="button_chem">Химия</a>
            <a href="{% url 'base:math' %}" class="button_math">Математика</a>
            <a href="{% url 'base:physics' %}" class="button_phis">Физика</a>
            <a href="{% url 'base:VR' %}" class="button_VR">VR</a>
            <a href="{% url 'base:geo' %}" class="button_geo">Геоинформатика</a>
            <a href="{% url 'base:informatics' %}" class="button_inform">Информатика</a>

            <div class="sketchfab-embed-wrapper"> <iframe title="Soda Bottle" frameborder="0" 
        allowfullscreen mozallowfullscreen="true" webkitallowfullscreen="true" allow="autoplay; fullscreen; xr-spatial-tracking" 
        xr-spatial-tracking execution-while-out-of-viewport execution-while-not-rendered web-share width="700" height="500" 
        src="https://sketchfab.com/models/4bf14705154b443f9e1c845d133bf5ec/embed?autostart=1&ui_hint=0"> 
        </iframe> </div>
            
            <p id="title">Погрузись в интересный мир ИНЖЕНЕРНОЙ школы</p>
        {% endblock %}
    </body>
<html>

base/templates/chemistry.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/geo.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a-scene id="img_360">
      <a-sky src="../static/d.jpg" rotation="0 -130 0"></a-sky>
    </a-scene>
    
    <div class="content_geo">
        <div>
        </div>
    </div>
    
    <a href="{% url 'base:main' %}" class="button">Главная</a>
{% endblock %}

base/templates/info.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Информация{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/informatics.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/math.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/physics.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Добавить{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>

{% endblock %}

base/templates/projects.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Проекты{% endblock %}

{% block content %}
    <a href="{% url 'base:main' %}" class="button">Главная</a>
    <div class="all">
    {% for i in projects %}
        <div class="project">
            <h1>{{i.title}}</h1>
            <h1>{{i.text}}</h1>
        </div>
    {% endfor %}
    </div>
    <a href="{% url 'base:add_project' %}" id="add">Добавить</a>
  
    
{% endblock %}